spring:
  datasource:
    url: jdbc:postgresql://localhost:3242/domain_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8080

name:
  com:
    api:
      token: 2654afc89abd16d01213a0fecadee55cded0ef7b
      username: vannraruos@gmail.com
app:
  domain:
    base-url: psa-khmer.world
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true